// GENERATED FILE — do not edit by hand.
// Run `pnpm gen:capabilities` to refresh. Derived by walking the import
// graph (see tool-capabilities.derive.ts) and by reading the tool copy out
// of tools-grid.tsx. tool-capabilities.test.ts fails when this drifts.
//
// 227 routes · 102 need AI · 70 use a browser.
// 92 are /tools/* · 35 need AI · 92 carry copy.

export const TOOL_CAPABILITIES = [
  { route: "/", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/about", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/activity", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/agent", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/agent/autopilot", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/agent/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/ai-visibility", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/ai-visibility/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/algorithm-updates", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Algorithm updates", description: "Timeline of every Google algorithm update with confirmed dates. Correlate against your traffic drops." },
  { route: "/annotations", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/ask", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/audits", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/audits/[id]", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/audits/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/audits/diff", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/author-authority", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/automations", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/automations/overview", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/automations/templates", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/backlinks", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/backlinks/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/bot-logs", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/brand-monitor", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/brand-monitor/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/brand-serp", needsAI: false, aiUsage: "none", usesBrowser: true },
  { route: "/broken-links", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/broken-links/c/[clientId]", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/cannibalization", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/cannibalization/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/capacity", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/capture", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/chats", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/citations", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/citations/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/clients", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/clients/[id]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/clients/[id]/ai-audit", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/clients/[id]/ai-audit/[auditId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/clients/[id]/automations", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/clients/[id]/edit", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/clients/[id]/onboarding", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/clients/[id]/plan", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/clients/[id]/queue", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/clients/import", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/clients/new", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/compare", needsAI: false, aiUsage: "none", usesBrowser: true },
  { route: "/competitors", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/competitors/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/competitors/playbook", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/connect", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/content-factory", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/content-gap", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/content-gap/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/csv-import", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/cwv", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/cwv/archive", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/cwv/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/digest", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/docs", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/docs/[slug]", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/embed/grader", needsAI: false, aiUsage: "none", usesBrowser: true },
  { route: "/findings/c/[clientId]", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/gbp", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/gbp/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/gbp/c/[clientId]/reviews", needsAI: true, aiUsage: "partial", usesBrowser: false },
  { route: "/grader", needsAI: false, aiUsage: "none", usesBrowser: true },
  { route: "/guest-posts/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/history", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/image-audit", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/image-audit/c/[clientId]", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/import", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/invite/[token]", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/invoices", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/invoices/[id]", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/invoices/new", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/keywords", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/keywords/[id]/screenshots", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/keywords/[id]/serp", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/keywords/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/knowledge", needsAI: false, aiUsage: "none", usesBrowser: false, title: "SEO knowledge hub", description: "Ranking signals, topical authority, blogging rules, page-speed by stack, GBP playbook, knowledge graph, rich snippets, E-E-A-T — the in-app reference." },
  { route: "/knowledge-panel", needsAI: false, aiUsage: "none", usesBrowser: true },
  { route: "/knowledge/top-sites", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/landing-perf", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/landing-perf/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/leads", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/learn", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/link-building", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/link-building/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/link-building/library", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/link-building/prospects", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/links", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/local-grid", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/local-grid/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/local-rank", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/local-rank/c/[clientId]", needsAI: false, aiUsage: "none", usesBrowser: true },
  { route: "/login", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/meta-rewrite", needsAI: true, aiUsage: "required", usesBrowser: true, title: "Meta rewrite batch (low-CTR)", description: "Pulls GSC data, finds your worst CTR vs position. AI rewrites title + meta in 2 variants per page. One-click push to WordPress if connected." },
  { route: "/meta-rewrite/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/monitor", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/monitor/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/morning", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/news", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/outreach", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/outreach/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/outreach/templates", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/portal/[token]", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/proposals", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/register", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/report-data", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/reports", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/reports/archive", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/reports/batch", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/reports/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/seo-chat", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/seo-chat/capabilities", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/serp-scans", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/settings/ai-learning", needsAI: true, aiUsage: "required", usesBrowser: false },
  { route: "/settings/ai-usage", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings/backup", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings/edge", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings/errors", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings/google", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings/health", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings/install", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/settings/team", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/shortcuts", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/snapshots", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/snapshots/compare", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/tasks", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/tasks/templates", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/title-tests", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/tools", needsAI: false, aiUsage: "none", usesBrowser: false },
  { route: "/tools/ads-funnel", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Ad Funnel Architect ⭐", description: "Multi-platform paid-ads strategy generator. Pick Meta, Google Search/Display/Shopping, LinkedIn, TikTok, or YouTube — get launch-ready copy variants, image-generation prompts, keyword bundles, funnel map, budget split, and tracking setup. Works on just AI." },
  { route: "/tools/ai-citation-tactics", needsAI: false, aiUsage: "none", usesBrowser: false, title: "AI citation tactics (per platform)", description: "Only 11% of cited domains overlap between ChatGPT and Perplexity. Niche-specific priority + concrete tactics for each platform: ChatGPT, Perplexity, Claude, Gemini, AI Overviews." },
  { route: "/tools/ai-overview", needsAI: true, aiUsage: "required", usesBrowser: false, title: "AI Overview optimizer", description: "AI scores your page's citation-worthiness for Google's AI Overviews. Specific changes to make ranked by impact." },
  { route: "/tools/ai-robots", needsAI: false, aiUsage: "none", usesBrowser: false, title: "AI-bot robots.txt audit ⭐", description: "Which AI crawlers (GPTBot, ClaudeBot, PerplexityBot, Google-Extended, etc.) can currently reach this site? Per-bot status + a copy-paste patch you can flip Allow/Disallow per line before pasting into robots.txt." },
  { route: "/tools/ai-schema", needsAI: true, aiUsage: "required", usesBrowser: false, title: "AI schema generator (from URL)", description: "Paste any URL — AI fetches, classifies content type, emits valid JSON-LD grounded in actual on-page content. Won't invent fields that aren't there." },
  { route: "/tools/aio-passage", needsAI: true, aiUsage: "required", usesBrowser: false, title: "AI Overview passage optimizer ⭐", description: "AIs cite 134-167 word self-contained passages. Paste a draft OR analyze a live URL — we split it, score each chunk on length / self-containment / Q→A / specifics / citations, and AI-rewrite low scorers in one batch." },
  { route: "/tools/anchor-distribution", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Anchor-text distribution", description: "Per-URL anchor frequency, internal vs external split, exact-match % over-optimization detection, brand variation check." },
  { route: "/tools/auto-link", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Auto-link suggester (RankMath-style)", description: "Paste content + your internal page list. AI proposes contextual internal links — exact anchor + target — to add." },
  { route: "/tools/backlink-discovery", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Backlink discovery", description: "DuckDuckGo + Common Crawl + crawl-to-confirm. Finds real verified backlinks with anchor text + rel. Closes the Ahrefs gap as much as is possible without a paid index." },
  { route: "/tools/bing", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Bing Webmaster Tools", description: "Free Bing organic data — top queries, top pages, crawl issues, URL submission. Add a free Bing API key once." },
  { route: "/tools/branded-split", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Branded vs non-branded GSC split", description: "28-day clicks split with delta vs prior 28 days, separately for branded and non-branded queries. Different drops, different fixes." },
  { route: "/tools/browser-agent", needsAI: true, aiUsage: "required", usesBrowser: true, title: "Browser agent (goal-driven)", description: "Plain-English goal + a starting URL. Headless Chrome reads the page, decides the next step, and narrates each move with a screenshot. Replaces 'I need an API for that site' with browser automation." },
  { route: "/tools/bulk-alt", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Bulk image alt-text generator", description: "Crawl a URL, AI writes SEO alt text for every image based on nearby context. RankMath bulk image SEO equivalent." },
  { route: "/tools/bulk-scan", needsAI: false, aiUsage: "none", usesBrowser: true, title: "Bulk URL scanner", description: "Paste up to 25 URLs. Run the full health check on each in parallel + save every result as a snapshot. Sortable table." },
  { route: "/tools/cannibalization", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Keyword cannibalization", description: "Finds queries where 2+ of your pages compete in the SERP — Google can't pick a winner, both suffer. GSC-powered, severity-ranked, suggests which page to keep." },
  { route: "/tools/canonical-audit", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Canonical conflict detector", description: "Crawl + flag every page where rel=canonical is missing, multiple, off-host, broken, redirect-target, or conflicts with noindex. Catches the silent indexation killer." },
  { route: "/tools/cluster", needsAI: true, aiUsage: "required", usesBrowser: true, title: "Topic cluster builder", description: "Head topic → mine PAA + autocomplete + Reddit → AI assembles 1 pillar + 15-20 spokes with slugs, intent, format, and an interlinking map. The 1-day strategy plan, in 60 seconds." },
  { route: "/tools/code-generator", needsAI: true, aiUsage: "required", usesBrowser: false, title: "SEO code / plugin generator", description: "AI writes the code you need to apply SEO changes — WordPress plugins, .htaccess rules, Elementor HTML, Shopify Liquid, Next.js routes, schema markup. With install steps + live preview." },
  { route: "/tools/content-grader", needsAI: false, aiUsage: "none", usesBrowser: true, title: "Content grader (Surfer / Clearscope replacement)", description: "Pulls top 10 SERP results, builds a TF-IDF corpus, scores your draft on length / term coverage / density. Free, browser-mode." },
  { route: "/tools/content-helpers", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Cover-image prompts + category suggester", description: "Two AI helpers: 3 image-gen prompts in distinct visual styles for any post, plus primary category + 5-10 SEO tags scoped to your existing taxonomy." },
  { route: "/tools/content-score", needsAI: true, aiUsage: "partial", usesBrowser: false, title: "Content scorer", description: "Paste content + target keyword. AI scores readability, density, structure, suggests LSI terms + specific edits." },
  { route: "/tools/crux", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Real-user CWV (CrUX)", description: "Real Chrome user data for one URL, last 28 days. Good for finding which page is slow — but Google's ranking signal is origin-level, so check the CrUX Origin Summary before concluding you're fine. Free with a PageSpeed key." },
  { route: "/tools/crux-origin", needsAI: false, aiUsage: "none", usesBrowser: false, title: "CrUX Origin Summary", description: "Google's CWV ranking signal uses 28-day origin-level field data, not URL-level. Compare URL vs origin scopes side-by-side so you don't optimize the wrong thing." },
  { route: "/tools/disavow", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Disavow file generator", description: "Paste backlink list. Auto-flags toxic domains (spam TLDs, casino/payday/random subdomains) and emits a Google-spec disavow.txt." },
  { route: "/tools/dns-whois", needsAI: false, aiUsage: "none", usesBrowser: false, title: "DNS + WHOIS / RDAP", description: "A/AAAA/MX/NS/TXT/CAA + registrar + expiry. Catches missing SPF/DMARC/CAA, near-expiry domains, broken nameservers. No paid API — public RDAP." },
  { route: "/tools/domain-overview", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Domain overview", description: "Every signal we can check ourselves — HTTPS, security headers, schema, on-page basics, indexed-pages estimate. Plus links to free external checkers for DA/DR." },
  { route: "/tools/eeat-audit", needsAI: true, aiUsage: "required", usesBrowser: false, title: "E-E-A-T audit", description: "Score any URL on Experience / Expertise / Authoritativeness / Trust. Detects bylines, schema, citations, trust pages, then AI writes a fix punch list." },
  { route: "/tools/external", needsAI: false, aiUsage: "none", usesBrowser: false, title: "External tools launchpad", description: "Paste a URL or keyword once → all 28 external tools (Moz DA, Ahrefs, SSL Labs, Wayback, etc.) open with that context pre-filled." },
  { route: "/tools/facet-trap", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Faceted-nav crawl-trap detector", description: "Filter / sort / pagination params can balloon a crawl from thousands to millions of near-duplicates. We crawl + group URLs by query shape and flag groups needing canonical/noindex protection." },
  { route: "/tools/freshness", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Freshness audit ⭐", description: "AI-search systems skip undated or stale pages. Fetches every freshness signal (HTTP header, meta tags, JSON-LD dateModified, <time> elements, visible 'Last updated' text) and gives you a ready-to-paste patch." },
  { route: "/tools/gbp-reply", needsAI: true, aiUsage: "partial", usesBrowser: false, title: "GBP review reply AI ⭐", description: "Pull GBP reviews, AI drafts a reply per review (tone matched to star rating), you approve or edit, post via the GBP API — full loop in one screen." },
  { route: "/tools/geo-rewrite", needsAI: true, aiUsage: "required", usesBrowser: false, title: "GEO rewrite workbench ⭐", description: "One click: audit (cn/global) → compiled rewrite instructions → LLM rewrite → GEU quality guard. Fact-breaking rewrites are rejected with reasons." },
  { route: "/tools/geo-score", needsAI: true, aiUsage: "required", usesBrowser: false, title: "GEO composite score ⭐", description: "Weighted scorecard for AI search visibility — citability, brand authority, content E-E-A-T, technical, schema, platform tactics. Forces you to fix the weakest leg first." },
  { route: "/tools/geo-swot", needsAI: true, aiUsage: "required", usesBrowser: true, title: "GEO SWOT", description: "Strengths, weaknesses, opportunities and threats for AI-search visibility, reasoned from the last 30 days of AI visibility checks for a client." },
  { route: "/tools/geo-swot/c/[clientId]", needsAI: true, aiUsage: "required", usesBrowser: true },
  { route: "/tools/github-pr", needsAI: false, aiUsage: "none", usesBrowser: false, title: "GitHub PR generator for SEO fixes", description: "For sites without a CMS write-bridge (Next.js / custom code), open a structured PR with a checklist of SEO fixes for your developer to implement." },
  { route: "/tools/gsc-coverage", needsAI: true, aiUsage: "partial", usesBrowser: false, title: "GSC index coverage (batch)", description: "Paste 60 URLs, hit GSC URL Inspection for each. See which are indexed, blocked, or excluded — and the reason. Daily indexation check." },
  { route: "/tools/headers", needsAI: false, aiUsage: "none", usesBrowser: false, title: "HTTP headers + redirect chain", description: "Trace every redirect step + show full HTTP response headers at each hop. Critical for debugging canonicalization, redirects, and CDN config." },
  { route: "/tools/health-check", needsAI: false, aiUsage: "none", usesBrowser: true, title: "Full SEO health check ⭐", description: "One URL → audit + robots + hreflang + security + Core Web Vitals + image audit + redirect chain in parallel. Save snapshots to compare before / after." },
  { route: "/tools/hreflang", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Hreflang validator", description: "Checks all hreflang tags (HTML + HTTP), validates format, x-default, self-reference, and reciprocal links across language variants." },
  { route: "/tools/hreflang-gen", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Hreflang generator", description: "Paste language-region URL pairs, emit HTML / Link-header / sitemap blocks with x-default validation." },
  { route: "/tools/image-gen", needsAI: true, aiUsage: "required", usesBrowser: false, title: "AI image generation (BYO OpenAI key)", description: "DALL·E 3 hero / OG / illustrative images. Aspect + quality + style controls. Output downloaded directly — no server storage." },
  { route: "/tools/indexnow", needsAI: false, aiUsage: "none", usesBrowser: false, title: "IndexNow submitter", description: "Push fresh URLs to Bing, Yandex, Naver, Seznam in seconds. Free, no API key — one verification file per host." },
  { route: "/tools/intent-classifier", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Bulk search-intent classifier", description: "Paste 200 queries — AI labels each as info / nav / commercial / transactional / local + suggests content format. Falls back to regex if AI not configured." },
  { route: "/tools/internal-linking", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Internal linking suggester", description: "Crawl your site, find pages that mention your target keyword without linking to your target URL. The fastest way to compound on-site authority." },
  { route: "/tools/keyword-difficulty", needsAI: true, aiUsage: "required", usesBrowser: true, title: "Keyword difficulty", description: "Heuristic 0-100 score from real SERP signals — big-brand presence, SERP features, title competitiveness. AI summary if your AI key is configured." },
  { route: "/tools/link-checker", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Link analyzer", description: "Paste any URL → every <a> link classified internal/external + dofollow/nofollow, with anchor text frequency. Critical pre-publish check." },
  { route: "/tools/link-graph", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Internal-link analyser", description: "Crawl + build link graph. Surfaces orphan pages and proposes top-3 source pages for each via TF-IDF cosine similarity. CSV / JSON export." },
  { route: "/tools/link-recommender", needsAI: true, aiUsage: "required", usesBrowser: false, title: "AI internal-link recommender", description: "Crawl your site + AI proposes 3-5 internal links with anchor + target + context snippet. Closes the gap on internal-linking opportunities humans miss." },
  { route: "/tools/llms-txt", needsAI: true, aiUsage: "partial", usesBrowser: false, title: "llms.txt manager", description: "Generate + validate llms.txt — the emerging standard for telling AI crawlers what your site is about." },
  { route: "/tools/local-cwv", needsAI: false, aiUsage: "none", usesBrowser: true, title: "Local Core Web Vitals (no PSI key)", description: "Measures LCP / FCP / CLS / TBT directly from PerformanceObserver. Lighthouse-equivalent 0-100 score, resource breakdown, top fixes by impact. No PageSpeed quota." },
  { route: "/tools/meta-tag-generator", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Meta tag generator", description: "Generates 3 angle-varied title + meta description options for any page, with SERP preview + Open Graph tags. Copy-paste HTML ready." },
  { route: "/tools/migration-map", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Migration redirect-map generator", description: "Old URL list + new URL list → 301 map. Token-overlap + path similarity scoring. Outputs Nginx, Apache .htaccess, and Next.js redirect blocks." },
  { route: "/tools/migration-parity", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Migration URL-parity auditor", description: "Pre/post-launch URL parity check. Surfaces 404s, drifted redirects, off-host hops. Companion to the migration map generator." },
  { route: "/tools/mobile-friendly", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Mobile-friendly checker", description: "Google deprecated theirs in 2023; this replaces it. Viewport, charset, responsive images, fixed-width elements, tap-target sizes, intrusive interstitials." },
  { route: "/tools/news-headline", needsAI: true, aiUsage: "required", usesBrowser: false, title: "News SEO — headline audit", description: "Score journalistic headlines for Top Stories fit, AP-style hook, length. AI suggests 3-5 alternates." },
  { route: "/tools/og-image", needsAI: false, aiUsage: "none", usesBrowser: false, title: "OG image generator", description: "1200×630 PNG cover image from a title + brand. 4 templates rendered in headless Chrome. No paid AI image API." },
  { route: "/tools/outreach-personalize", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Outreach personalizer", description: "Paste prospect URL + your generic template. AI mines their site for recent posts and topical signals, rewrites your opener with a specific reference. 2% → 15% reply rates." },
  { route: "/tools/pagerank", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Internal PageRank simulator", description: "Crawls site, builds link graph, runs 30 iterations of PageRank. Surfaces authority hubs and starved pages so you know where to add internal links." },
  { route: "/tools/perf-budget", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Performance budget enforcement", description: "Define byte / request / Core Web Vitals budgets. We measure actuals via PageSpeed + CrUX and surface every line item over budget. Catch regressions before prod." },
  { route: "/tools/person-schema", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Person schema generator (E-E-A-T) ⭐", description: "Person JSON-LD is the top E-E-A-T signal in 2026 — Google's AI Mode uses it for entity verification. Fill in author details, get a copy-paste <script>." },
  { route: "/tools/pixel-preview", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Pixel preview", description: "See exactly how your title + meta description will look in Google's SERP. Click pre-cut, character counts, mobile + desktop." },
  { route: "/tools/plagiarism", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Plagiarism + AI detector", description: "AI-likelihood + originality scores on any draft. Flags AI-template phrases. Links to Copyleaks, GPTZero, Originality.ai for definitive web check." },
  { route: "/tools/programmatic-seo", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Programmatic SEO toolkit", description: "CSV + four templates → 100s-1000s of landing pages with sitemap + interlinking. Ideal for city × service combos and SaaS comparison pages." },
  { route: "/tools/rank-where", needsAI: false, aiUsage: "none", usesBrowser: true, title: "Where do I rank? (country-aware) ⭐", description: "Find your exact position for any keyword × country in Google's top 100. See who outranks you, AI Overview presence + citation, specific fixes to climb." },
  { route: "/tools/reddit-research", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Reddit research", description: "Reddit is in 40% of LLM citations. Mine real questions and pain points your audience asks — perfect FAQ + content brief seeds." },
  { route: "/tools/redirects-bulk", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Bulk redirect-chain tester", description: "Paste up to 100 URLs. Trace every redirect hop in parallel. Surfaces chains, loops, mixed-scheme jumps, broken 301s. Migration-day staple." },
  { route: "/tools/redirects-manager", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Redirect manager + 404 monitor", description: "CRUD UI for 301/302/307/308/410 rules. 404 log with one-click 'turn this into a redirect'. POST to /api/v1/track-404 to log automatically." },
  { route: "/tools/refresh", needsAI: true, aiUsage: "required", usesBrowser: true, title: "Content refresh detector", description: "Compare your published page to top-10 SERP. Surfaces missing topics, missing sections, plus a concrete refresh plan a writer can execute." },
  { route: "/tools/render", needsAI: false, aiUsage: "none", usesBrowser: true, title: "JS render + screenshot", description: "Render any URL in headless Chrome — post-hydration HTML, full-page screenshot, redirect chain, response headers, console + network errors. Critical for SPAs." },
  { route: "/tools/reputation-abuse-risk", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Site reputation abuse risk scan", description: "Google now algorithmically demotes sections 'starkly different' from the main site. Crawl + group by path + score topical coherence so you don't lose authority." },
  { route: "/tools/robots", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Robots.txt + sitemap validator", description: "Fetch + check robots.txt, sitemap.xml. Find blocked URLs, broken sitemap entries, indexability issues." },
  { route: "/tools/robots-history", needsAI: false, aiUsage: "none", usesBrowser: false, title: "robots.txt history + diff", description: "Snapshot any host's robots.txt over time. Catches accidental Disallow: / disasters before they hurt indexing." },
  { route: "/tools/schema", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Schema markup generator", description: "AI generates valid JSON-LD for Article, LocalBusiness, FAQ, Product, Recipe, Event. Paste your URL — we extract the rest." },
  { route: "/tools/schema-validate", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Schema validator (live URL)", description: "Fetches the URL, extracts every JSON-LD block, validates required fields by type. Complements the AI schema generator." },
  { route: "/tools/screenshot-import", needsAI: true, aiUsage: "required", usesBrowser: false, title: "Screenshot import — paid-tool data parser", description: "Drag a screenshot from Ahrefs / Semrush / GSC / GA4. AI vision extracts the structured data so you can stop paying for tools you only use occasionally." },
  { route: "/tools/search-volume", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Search-volume estimator", description: "Free directional volume bucket. Combines Google Trends, Google + Bing autocomplete, SERP characteristics. No paid keyword DB." },
  { route: "/tools/security", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Security headers + SSL grade", description: "Mozilla Observatory + SSL Labs. Free, no key. Surface fix-it actions for security ranking signals." },
  { route: "/tools/serp-features", needsAI: false, aiUsage: "none", usesBrowser: true, title: "SERP feature tracker (AIO + FS + PAA)", description: "Capture SERP snapshots over time — AI Overview citations, featured snippets, PAA questions. Surfaces snippet-takeover opportunities." },
  { route: "/tools/serp-volatility", needsAI: false, aiUsage: "none", usesBrowser: false, title: "SERP volatility tracker", description: "Day-over-day position shifts across every tracked keyword. Volatility score spikes during algorithm updates — pause big content moves when stormy." },
  { route: "/tools/sitemap", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Sitemap generator", description: "Crawl any site, generate sitemap.xml + plain-text URL list + human-readable HTML index. Respects robots.txt by default." },
  { route: "/tools/social-preview", needsAI: false, aiUsage: "none", usesBrowser: false, title: "OG / Twitter card preview", description: "Render OG + Twitter card visually. Catches missing og:image, relative URLs, missing twitter:card — the silent killers of social CTR." },
  { route: "/tools/soft-404", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Soft 404 catcher", description: "Crawl + flag pages that return 200 but smell like 404s — thin content, '404' / 'page not found' text patterns, generic error titles. Silent indexation killers." },
  { route: "/tools/summarizer", needsAI: true, aiUsage: "required", usesBrowser: false, title: "AI content summarizer", description: "Long content → TL;DR + 5-7 takeaways + meta description + tweetable quote. Yoast Premium AI Summarize equivalent." },
  { route: "/tools/sxo", needsAI: true, aiUsage: "required", usesBrowser: false, title: "SXO — Search Experience Optimization", description: "Audits user-experience signals Google now weights heavily: page promise, time-to-answer, next step, friction, Core Web Vitals. Persona-driven recommendations." },
  { route: "/tools/traffic-drop", needsAI: true, aiUsage: "optional", usesBrowser: false, title: "Why did my traffic drop?", description: "Pulls last 28 vs prev 28 days from GSC. Diffs queries + pages, cross-references curated Google algorithm-update timeline, AI ranks the most likely cause." },
  { route: "/tools/trending", needsAI: true, aiUsage: "required", usesBrowser: true, title: "Trending content ideas", description: "Mines Google Trends rising queries, autocomplete a-z expansion, People Also Ask, related searches, Reddit threads. AI synthesises 10-15 publish-ready ideas." },
  { route: "/tools/uptime", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Uptime + TTFB monitor", description: "Add URLs to ping. Status code, latency, expected-text match. Self-hosted alternative to UptimeRobot." },
  { route: "/tools/utm-attribution", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Multi-touch attribution (UTM)", description: "First-touch, last-touch, assisted, linear, position-based attribution from any UTM-tagged touch CSV. No CRM needed." },
  { route: "/tools/wayback", needsAI: false, aiUsage: "none", usesBrowser: false, title: "Wayback Machine timeline", description: "How did a URL look 2 years ago? Internet Archive CDX, free, no key." },
  { route: "/tools/wp-hack-scan", needsAI: false, aiUsage: "none", usesBrowser: false, title: "WordPress hack / malware scan ⭐", description: "Probes a live WP site for compromise indicators: backdoor files, exposed configs, JS injection, hidden iframes, spam injection, cloaking. Returns containment + cleanup + prevention playbook." },
  { route: "/tools/youtube", needsAI: false, aiUsage: "none", usesBrowser: false, title: "YouTube keyword research", description: "Real video data — view counts, channels, recurring tag phrases. Free YouTube Data API tier (100 searches a day)." },
  { route: "/tools/youtube-audit", needsAI: true, aiUsage: "required", usesBrowser: false, title: "YouTube SEO audit", description: "Paste any YouTube URL → 14-point checklist (title, description, chapters, hashtags, tags, captions, thumbnail, like ratio, freshness) + AI fix steps. Free — uses oEmbed + watch-page scrape." },
  { route: "/welcome", needsAI: false, aiUsage: "none", usesBrowser: false },
] as const;
